# Global settings applied to the whole site.
[build]
  command = "npm run build"
  publish = "dist" # Vite build çıktısını "dist" içine koyar


[build.environment]
  NODE_VERSION = "20.14.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
